# Generated by Django 5.2.4 on 2025-09-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
