# Generated by Django 5.2.4 on 2025-09-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_chapter_pdf_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="pdf_url",
            field=models.CharField(max_length=200),
        ),
    ]
