# Generated by Django 5.2.4 on 2025-09-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_chapter_pdf_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="pdf_url",
        ),
        migrations.AddField(
            model_name="chapter",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="chapters/"),
        ),
    ]
