# Generated by Django 5.2.4 on 2025-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_chapter_pdf_url_chapter_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="with_solution",
            field=models.BooleanField(default=False),
        ),
    ]
