# Generated by Django 5.2.4 on 2025-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_exam_with_solution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="content",
        ),
        migrations.AddField(
            model_name="exercise",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="exercises/"),
        ),
    ]
