# Generated by Django 5.2.4 on 2025-09-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_exercise_content_exercise_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="course",
        ),
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.schoollevel",
            ),
            preserve_default=False,
        ),
    ]
